spring:
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

app:
  task-execution-delay: 120_000 # 2 min
  #  task-execution-delay: 10_000 # 10 s
  datasource:
    settings:
      url: jdbc:postgresql://localhost:${DB_SETTINGS_PORT}/settings
      username: ${DB_SETTINGS_USERNAME}
      password: ${DB_SETTINGS_PASSWORD}
      driver-class-name: org.postgresql.Driver
  jdbc:
    users:
      batch-size: 10
  jta:
    atomikos:
      pool-size: 10
  security:
    encryptor:
      password: ${ENCRYPTOR_PASSWORD}
      salt: ${ENCRYPTOR_SALT}

#logging:
#  level:
#    org.springframework.beans: debug
#    org.springframework.jdbc.datasource.init: debug
#    org.springframework: DEBUG
#    org.springframework.jdbc.datasource: DEBUG;
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.beans.factory.support: DEBUG

