spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

app:
  task-execution-delay: 120000 # 2 min
  datasource:
    settings:
      url: jdbc:postgresql://localhost:${DB_SETTINGS_PORT}/settings
      username: ${DB_SETTINGS_USERNAME}
      password: ${DB_SETTINGS_PASSWORD}
      driver-class-name: org.postgresql.Driver
  security:
    encryptor:
      password: ${ENCRYPTOR_PASSWORD}
      salt: ${ENCRYPTOR_SALT}

#logging:
#  level:
#    org.springframework: DEBUG
#    org.springframework.jdbc.datasource: DEBUG;
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.beans.factory.support: DEBUG

