CREATE TABLE IF NOT EXISTS users
(
    id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name    varchar(50)        NOT NULL,
    last_name     varchar(50)        NOT NULL,
    sex           varchar(1) CHECK (sex IN ('M', 'F')),
    date_of_birth date,
    nationality   char(2)            NOT NULL,
    user_name     varchar(50) UNIQUE NOT NULL,
    password      varchar(40)        NOT NULL
);